import { db } from '@/db';
import { scans } from '@/db/schema';

async function main() {
    const now = Date.now();
    const oneDayMs = 24 * 60 * 60 * 1000;
    
    const sampleScans = [
        // Chrome scans
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 0.5 * oneDayMs).toISOString(),
            browser: 'Chrome',
            os: 'Windows',
            deviceType: 'desktop',
            country: 'United States',
            city: 'New York',
            region: 'New York',
            latitude: '40.7128',
            longitude: '-74.0060',
            timezone: 'America/New_York',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            ipAddress: '192.168.1.101',
            isp: 'Comcast',
            referrer: 'https://google.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 1.2 * oneDayMs).toISOString(),
            browser: 'Chrome',
            os: 'Android',
            deviceType: 'mobile',
            country: 'United States',
            city: 'Los Angeles',
            region: 'California',
            latitude: '34.0522',
            longitude: '-118.2437',
            timezone: 'America/Los_Angeles',
            userAgent: 'Mozilla/5.0 (Linux; Android 13; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.144 Mobile Safari/537.36',
            ipAddress: '172.16.254.1',
            isp: 'Verizon',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 2.1 * oneDayMs).toISOString(),
            browser: 'Chrome',
            os: 'MacOS',
            deviceType: 'desktop',
            country: 'United Kingdom',
            city: 'London',
            region: 'England',
            latitude: '51.5074',
            longitude: '-0.1278',
            timezone: 'Europe/London',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            ipAddress: '10.0.0.45',
            isp: 'BT Group',
            referrer: 'https://facebook.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 2.8 * oneDayMs).toISOString(),
            browser: 'Chrome',
            os: 'iOS',
            deviceType: 'mobile',
            country: 'Germany',
            city: 'Berlin',
            region: 'Berlin',
            latitude: '52.5200',
            longitude: '13.4050',
            timezone: 'Europe/Berlin',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/120.0.6099.119 Mobile/15E148 Safari/604.1',
            ipAddress: '198.51.100.23',
            isp: 'Vodafone',
            referrer: 'https://google.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 3.5 * oneDayMs).toISOString(),
            browser: 'Chrome',
            os: 'Android',
            deviceType: 'mobile',
            country: 'Japan',
            city: 'Tokyo',
            region: 'Tokyo',
            latitude: '35.6762',
            longitude: '139.6503',
            timezone: 'Asia/Tokyo',
            userAgent: 'Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',
            ipAddress: '203.0.113.45',
            isp: 'NTT',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 4.2 * oneDayMs).toISOString(),
            browser: 'Chrome',
            os: 'Windows',
            deviceType: 'desktop',
            country: 'United States',
            city: 'Chicago',
            region: 'Illinois',
            latitude: '41.8781',
            longitude: '-87.6298',
            timezone: 'America/Chicago',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
            ipAddress: '192.0.2.67',
            isp: 'Comcast',
            referrer: 'https://twitter.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 5.1 * oneDayMs).toISOString(),
            browser: 'Chrome',
            os: 'MacOS',
            deviceType: 'desktop',
            country: 'United Kingdom',
            city: 'Manchester',
            region: 'England',
            latitude: '53.4808',
            longitude: '-2.2426',
            timezone: 'Europe/London',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36',
            ipAddress: '198.18.0.89',
            isp: 'BT Group',
            referrer: 'https://facebook.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 6.3 * oneDayMs).toISOString(),
            browser: 'Chrome',
            os: 'iOS',
            deviceType: 'mobile',
            country: 'India',
            city: 'Mumbai',
            region: 'Maharashtra',
            latitude: '19.0760',
            longitude: '72.8777',
            timezone: 'Asia/Kolkata',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/119.0.6045.169 Mobile/15E148 Safari/604.1',
            ipAddress: '203.192.1.34',
            isp: null,
            referrer: 'https://google.com',
        },
        // Safari scans
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 0.8 * oneDayMs).toISOString(),
            browser: 'Safari',
            os: 'iOS',
            deviceType: 'mobile',
            country: 'United States',
            city: 'New York',
            region: 'New York',
            latitude: '40.7128',
            longitude: '-74.0060',
            timezone: 'America/New_York',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.1',
            ipAddress: '192.168.1.102',
            isp: 'Verizon',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 1.5 * oneDayMs).toISOString(),
            browser: 'Safari',
            os: 'MacOS',
            deviceType: 'desktop',
            country: 'United States',
            city: 'Los Angeles',
            region: 'California',
            latitude: '34.0522',
            longitude: '-118.2437',
            timezone: 'America/Los_Angeles',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15',
            ipAddress: '172.16.0.89',
            isp: 'Comcast',
            referrer: 'https://google.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 2.4 * oneDayMs).toISOString(),
            browser: 'Safari',
            os: 'iOS',
            deviceType: 'tablet',
            country: 'Germany',
            city: 'Munich',
            region: 'Bavaria',
            latitude: '48.1351',
            longitude: '11.5820',
            timezone: 'Europe/Berlin',
            userAgent: 'Mozilla/5.0 (iPad; CPU OS 17_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.1',
            ipAddress: '198.51.100.78',
            isp: 'Vodafone',
            referrer: 'https://facebook.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 3.2 * oneDayMs).toISOString(),
            browser: 'Safari',
            os: 'iOS',
            deviceType: 'mobile',
            country: 'Japan',
            city: 'Osaka',
            region: 'Osaka',
            latitude: '34.6937',
            longitude: '135.5023',
            timezone: 'Asia/Tokyo',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1',
            ipAddress: '203.0.113.90',
            isp: 'NTT',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 4.7 * oneDayMs).toISOString(),
            browser: 'Safari',
            os: 'MacOS',
            deviceType: 'desktop',
            country: 'United Kingdom',
            city: 'London',
            region: 'England',
            latitude: '51.5074',
            longitude: '-0.1278',
            timezone: 'Europe/London',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15',
            ipAddress: '10.0.0.123',
            isp: 'BT Group',
            referrer: 'https://twitter.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 5.9 * oneDayMs).toISOString(),
            browser: 'Safari',
            os: 'iOS',
            deviceType: 'mobile',
            country: 'India',
            city: 'Delhi',
            region: 'Delhi',
            latitude: '28.7041',
            longitude: '77.1025',
            timezone: 'Asia/Kolkata',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
            ipAddress: '203.192.1.45',
            isp: null,
            referrer: 'https://google.com',
        },
        // Firefox scans
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 1.0 * oneDayMs).toISOString(),
            browser: 'Firefox',
            os: 'Windows',
            deviceType: 'desktop',
            country: 'United States',
            city: 'Chicago',
            region: 'Illinois',
            latitude: '41.8781',
            longitude: '-87.6298',
            timezone: 'America/Chicago',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
            ipAddress: '192.0.2.156',
            isp: 'Verizon',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 2.6 * oneDayMs).toISOString(),
            browser: 'Firefox',
            os: 'Linux',
            deviceType: 'desktop',
            country: 'Germany',
            city: 'Berlin',
            region: 'Berlin',
            latitude: '52.5200',
            longitude: '13.4050',
            timezone: 'Europe/Berlin',
            userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0',
            ipAddress: '198.51.100.234',
            isp: 'Vodafone',
            referrer: 'https://facebook.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 3.8 * oneDayMs).toISOString(),
            browser: 'Firefox',
            os: 'Android',
            deviceType: 'mobile',
            country: 'United Kingdom',
            city: 'Manchester',
            region: 'England',
            latitude: '53.4808',
            longitude: '-2.2426',
            timezone: 'Europe/London',
            userAgent: 'Mozilla/5.0 (Android 13; Mobile; rv:121.0) Gecko/121.0 Firefox/121.0',
            ipAddress: '198.18.0.167',
            isp: null,
            referrer: 'https://google.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 5.5 * oneDayMs).toISOString(),
            browser: 'Firefox',
            os: 'MacOS',
            deviceType: 'desktop',
            country: 'Japan',
            city: 'Tokyo',
            region: 'Tokyo',
            latitude: '35.6762',
            longitude: '139.6503',
            timezone: 'Asia/Tokyo',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0',
            ipAddress: '203.0.113.178',
            isp: 'NTT',
            referrer: null,
        },
        // Edge scans
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 1.8 * oneDayMs).toISOString(),
            browser: 'Edge',
            os: 'Windows',
            deviceType: 'desktop',
            country: 'United States',
            city: 'New York',
            region: 'New York',
            latitude: '40.7128',
            longitude: '-74.0060',
            timezone: 'America/New_York',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
            ipAddress: '192.168.1.234',
            isp: 'Comcast',
            referrer: 'https://facebook.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 4.5 * oneDayMs).toISOString(),
            browser: 'Edge',
            os: 'Android',
            deviceType: 'tablet',
            country: 'Germany',
            city: 'Munich',
            region: 'Bavaria',
            latitude: '48.1351',
            longitude: '11.5820',
            timezone: 'Europe/Berlin',
            userAgent: 'Mozilla/5.0 (Linux; Android 13; SM-X706B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.144 Mobile Safari/537.36 EdgA/120.0.2210.86',
            ipAddress: '198.51.100.199',
            isp: null,
            referrer: 'https://twitter.com',
        },
    ];

    await db.insert(scans).values(sampleScans);
    
    console.log('✅ Scans test analytics seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});