import { db } from '@/db';
import { scans } from '@/db/schema';

async function main() {
    const now = Date.now();
    const oneDayMs = 24 * 60 * 60 * 1000;
    const oneHourMs = 60 * 60 * 1000;

    const sampleScans = [
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 6 * oneDayMs - 3 * oneHourMs).toISOString(),
            browser: 'Chrome',
            os: 'Windows',
            deviceType: 'desktop',
            country: 'United States',
            city: 'New York',
            region: 'New York',
            latitude: '40.7128',
            longitude: '-74.0060',
            ipAddress: '192.168.1.45',
            isp: 'Comcast',
            timezone: 'America/New_York',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            referrer: 'https://google.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 6 * oneDayMs - 8 * oneHourMs).toISOString(),
            browser: 'Safari',
            os: 'iOS',
            deviceType: 'mobile',
            country: 'United States',
            city: 'Los Angeles',
            region: 'California',
            latitude: '34.0522',
            longitude: '-118.2437',
            ipAddress: '10.0.0.123',
            isp: 'Verizon',
            timezone: 'America/Los_Angeles',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 5 * oneDayMs - 12 * oneHourMs).toISOString(),
            browser: 'Chrome',
            os: 'Android',
            deviceType: 'mobile',
            country: 'United Kingdom',
            city: 'London',
            region: 'England',
            latitude: '51.5074',
            longitude: '-0.1278',
            ipAddress: '172.16.0.88',
            isp: 'BT Group',
            timezone: 'Europe/London',
            userAgent: 'Mozilla/5.0 (Linux; Android 14; SM-G998B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.43 Mobile Safari/537.36',
            referrer: 'https://facebook.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 5 * oneDayMs - 5 * oneHourMs).toISOString(),
            browser: 'Firefox',
            os: 'Windows',
            deviceType: 'desktop',
            country: 'Germany',
            city: 'Berlin',
            region: 'Berlin',
            latitude: '52.5200',
            longitude: '13.4050',
            ipAddress: '198.51.100.42',
            isp: 'Vodafone',
            timezone: 'Europe/Berlin',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 4 * oneDayMs - 18 * oneHourMs).toISOString(),
            browser: 'Safari',
            os: 'MacOS',
            deviceType: 'desktop',
            country: 'United States',
            city: 'Chicago',
            region: 'Illinois',
            latitude: '41.8781',
            longitude: '-87.6298',
            ipAddress: '203.0.113.67',
            isp: 'Comcast',
            timezone: 'America/Chicago',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15',
            referrer: 'https://twitter.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 4 * oneDayMs - 10 * oneHourMs).toISOString(),
            browser: 'Chrome',
            os: 'Android',
            deviceType: 'mobile',
            country: 'Japan',
            city: 'Tokyo',
            region: 'Tokyo',
            latitude: '35.6762',
            longitude: '139.6503',
            ipAddress: '198.18.0.155',
            isp: 'NTT',
            timezone: 'Asia/Tokyo',
            userAgent: 'Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.43 Mobile Safari/537.36',
            referrer: 'https://google.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 4 * oneDayMs - 2 * oneHourMs).toISOString(),
            browser: 'Edge',
            os: 'Windows',
            deviceType: 'desktop',
            country: 'United Kingdom',
            city: 'Manchester',
            region: 'England',
            latitude: '53.4808',
            longitude: '-2.2426',
            ipAddress: '192.0.2.98',
            isp: null,
            timezone: 'Europe/London',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.2210.61',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 3 * oneDayMs - 20 * oneHourMs).toISOString(),
            browser: 'Chrome',
            os: 'iOS',
            deviceType: 'mobile',
            country: 'India',
            city: 'Mumbai',
            region: 'Maharashtra',
            latitude: '19.0760',
            longitude: '72.8777',
            ipAddress: '198.51.100.201',
            isp: 'Vodafone',
            timezone: 'Asia/Kolkata',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/120.0.6099.119 Mobile/15E148 Safari/604.1',
            referrer: 'https://facebook.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 3 * oneDayMs - 14 * oneHourMs).toISOString(),
            browser: 'Safari',
            os: 'iOS',
            deviceType: 'tablet',
            country: 'Germany',
            city: 'Munich',
            region: 'Bavaria',
            latitude: '48.1351',
            longitude: '11.5820',
            ipAddress: '203.0.113.142',
            isp: 'Vodafone',
            timezone: 'Europe/Berlin',
            userAgent: 'Mozilla/5.0 (iPad; CPU OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1',
            referrer: 'https://twitter.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 3 * oneDayMs - 7 * oneHourMs).toISOString(),
            browser: 'Firefox',
            os: 'MacOS',
            deviceType: 'desktop',
            country: 'United States',
            city: 'New York',
            region: 'New York',
            latitude: '40.7128',
            longitude: '-74.0060',
            ipAddress: '192.168.100.78',
            isp: 'Verizon',
            timezone: 'America/New_York',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14.2; rv:121.0) Gecko/20100101 Firefox/121.0',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 2 * oneDayMs - 22 * oneHourMs).toISOString(),
            browser: 'Chrome',
            os: 'Windows',
            deviceType: 'desktop',
            country: 'Japan',
            city: 'Osaka',
            region: 'Osaka',
            latitude: '34.6937',
            longitude: '135.5023',
            ipAddress: '198.18.1.234',
            isp: 'NTT',
            timezone: 'Asia/Tokyo',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            referrer: 'https://google.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 2 * oneDayMs - 16 * oneHourMs).toISOString(),
            browser: 'Safari',
            os: 'MacOS',
            deviceType: 'desktop',
            country: 'United Kingdom',
            city: 'London',
            region: 'England',
            latitude: '51.5074',
            longitude: '-0.1278',
            ipAddress: '172.16.254.88',
            isp: 'BT Group',
            timezone: 'Europe/London',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15',
            referrer: 'https://facebook.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 2 * oneDayMs - 9 * oneHourMs).toISOString(),
            browser: 'Chrome',
            os: 'Android',
            deviceType: 'mobile',
            country: 'India',
            city: 'Delhi',
            region: 'Delhi',
            latitude: '28.7041',
            longitude: '77.1025',
            ipAddress: '203.0.113.199',
            isp: null,
            timezone: 'Asia/Kolkata',
            userAgent: 'Mozilla/5.0 (Linux; Android 14; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.43 Mobile Safari/537.36',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 1 * oneDayMs - 19 * oneHourMs).toISOString(),
            browser: 'Firefox',
            os: 'Linux',
            deviceType: 'desktop',
            country: 'Germany',
            city: 'Berlin',
            region: 'Berlin',
            latitude: '52.5200',
            longitude: '13.4050',
            ipAddress: '198.51.100.77',
            isp: 'Vodafone',
            timezone: 'Europe/Berlin',
            userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0',
            referrer: 'https://google.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 1 * oneDayMs - 13 * oneHourMs).toISOString(),
            browser: 'Chrome',
            os: 'iOS',
            deviceType: 'mobile',
            country: 'United States',
            city: 'Los Angeles',
            region: 'California',
            latitude: '34.0522',
            longitude: '-118.2437',
            ipAddress: '10.0.100.45',
            isp: 'Comcast',
            timezone: 'America/Los_Angeles',
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/120.0.6099.119 Mobile/15E148 Safari/604.1',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 1 * oneDayMs - 6 * oneHourMs).toISOString(),
            browser: 'Safari',
            os: 'iOS',
            deviceType: 'tablet',
            country: 'Japan',
            city: 'Tokyo',
            region: 'Tokyo',
            latitude: '35.6762',
            longitude: '139.6503',
            ipAddress: '198.18.0.67',
            isp: 'NTT',
            timezone: 'Asia/Tokyo',
            userAgent: 'Mozilla/5.0 (iPad; CPU OS 17_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.1',
            referrer: 'https://twitter.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 20 * oneHourMs).toISOString(),
            browser: 'Edge',
            os: 'Windows',
            deviceType: 'desktop',
            country: 'United States',
            city: 'Chicago',
            region: 'Illinois',
            latitude: '41.8781',
            longitude: '-87.6298',
            ipAddress: '192.0.2.156',
            isp: 'Verizon',
            timezone: 'America/Chicago',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.2210.61',
            referrer: 'https://facebook.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 15 * oneHourMs).toISOString(),
            browser: 'Chrome',
            os: 'Android',
            deviceType: 'mobile',
            country: 'United Kingdom',
            city: 'Manchester',
            region: 'England',
            latitude: '53.4808',
            longitude: '-2.2426',
            ipAddress: '172.16.0.234',
            isp: 'BT Group',
            timezone: 'Europe/London',
            userAgent: 'Mozilla/5.0 (Linux; Android 13; OnePlus 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.43 Mobile Safari/537.36',
            referrer: null,
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 10 * oneHourMs).toISOString(),
            browser: 'Safari',
            os: 'MacOS',
            deviceType: 'desktop',
            country: 'Germany',
            city: 'Munich',
            region: 'Bavaria',
            latitude: '48.1351',
            longitude: '11.5820',
            ipAddress: '198.51.100.188',
            isp: null,
            timezone: 'Europe/Berlin',
            userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15',
            referrer: 'https://google.com',
        },
        {
            qrCodeId: 6,
            scannedAt: new Date(now - 4 * oneHourMs).toISOString(),
            browser: 'Firefox',
            os: 'Windows',
            deviceType: 'desktop',
            country: 'India',
            city: 'Mumbai',
            region: 'Maharashtra',
            latitude: '19.0760',
            longitude: '72.8777',
            ipAddress: '203.0.113.234',
            isp: 'Vodafone',
            timezone: 'Asia/Kolkata',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
            referrer: 'https://twitter.com',
        },
    ];

    await db.insert(scans).values(sampleScans);
    
    console.log('✅ Marketing scans seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});